name: Deployment
on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  vite-build:
    runs-on: ubuntu-latest
    steps:
      # install nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      # checkout the latest commit of the current branch
      - uses: actions/checkout@v3

      # install dependencies
      - run: npm ci

      # build the site
      - run: npm run build

  gh-pages-build:
    needs: vite-build
    runs-on: ubuntu-latest
    steps:
      # install nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: latest

      # checkout the repo
      - uses: actions/checkout@v3

      # for each branch in the repo except gh-pages, checkout the branch's latest commit, install dependencies, and build the site into a folder named after the branch
      - run: |
          BRANCHES=$(git branch -r | grep -v HEAD | grep -v gh-pages | grep -v dist | sed 's/origin\///')
          for BRANCH in $BRANCHES; do
            git checkout $BRANCH
            npm ci
            npm run build -- --outDir "dist/$BRANCH" --base "/$BRANCH" --force
          done
        shell: bash

      # switch to the gh-pages branch
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: dist

      # move the built site into the root directory
      - run: mv -f dist/* .
      - run: rm -rf dist

      # commit the changes
      - uses: EndBug/add-and-commit@v9
        with:
          add: .
          default_author: github_actions
          message: "Deploy ${{ github.push.after }} to GitHub Pages"
          push: true
